### ISSUE TITLE
How to use in Android Studio

### ISSUE THREAD

**Issue by xingag** [Q42/AndroidScrollingImageView#2]
Step 1. Add the JitPack repository to your build file

repositories {
    // ...
    maven { url "https://jitpack.io" }
}
Step 2. Add the dependency in the form

dependencies {
    compile 'com.github.Q42:AndroidScrollingImageView:1.0'
}

I can not understand how to use

**Comment by tsuijten** [comment]
Do you have an Android project with gradle?

**Comment by xingag** [comment]
yes；I had download the source and manual import a part of code，and it do well ，thanks
