### ISSUE TITLE
Failed to resolve: com.github.Q42:AndroidScrollingImageView:1.1

### ISSUE THREAD

**Issue by JonathanImperato** [Q42/AndroidScrollingImageView#3]
Error:(20, 13) Failed to resolve: com.github.Q42:AndroidScrollingImageView:1.1
It says this, what is wrong?
I put it in the app build.gradle not in the top-level build gradle. Is this the bug?
It should not.

**Comment by tsuijten** [comment]
Hi, did you add the repository in your gradle file?

```
repositories {
    maven { url "https://jitpack.io" }
}
```

**Comment by JonathanImperato** [comment]
Yes I did
