### ISSUE TITLE
gradle failed

### ISSUE THREAD

**Issue by shanmmukha1589** [Q42/AndroidScrollingImageView#4]
Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.github.Q42:AndroidScrollingImageView:1.1] /home/om/AndroidStudioProjects/GoRide/app/build/intermediates/exploded-aar/com.github.Q42/AndroidScrollingImageView/1.1/AndroidManifest.xml
>     Suggestion: use tools:overrideLibrary="com.q42.android.scrollingimageview" to force usage

**Comment by tsuijten** [comment]
You should set set `minSdkVersion` to 16

```
android {
    defaultConfig {
        minSdkVersion 16
    }
```

**Comment by Morteza-Rastgoo** [comment]
why not backward compatible with more api levels?

**Comment by vishalpatel1327** [comment]
android {
    defaultConfig {
        minSdkVersion 16
    }

still error

Error:(30, 13) Failed to resolve: 'com.github.Q42:AndroidScrollingImageView:1.3.2
<a href="openFile:/home/vishal/Android/Studio-workspace/Demo-Projects/Splash/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by akulkarni9** [comment]
This happened to me in android studio 3.1.2, my `minSdkVersion` is 21 and `targetSdkVersion` is 27. I even added `classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'` to project's gradle, but same error repeats. I'm also using `implementation 'com.jakewharton:butterknife:8.5.1'` in my project.
