### ISSUE TITLE
Error inflating class scrollingimageview Android 4.0.4

### ISSUE THREAD

**Issue by dibakarece** [Q42/AndroidScrollingImageView#6]
11-16 13:26:05.080: E/AndroidRuntime(3447): java.lang.RuntimeException: Unable to start activity ComponentInfo{scrollingimageview.android.q42.com.sampleapp/scrollingimageview.android.q42.com.sampleapp.MainActivity}: android.view.InflateException: Binary XML file line #28: Error inflating class scrollingimageview.android.q42.com.sampleapp.ScrollingImageView

**Comment by vishalpatel1327** [comment]
I also having same issue   in 1.3.2 version
